{% set name = "napari-filaments" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari_filaments-{{ version }}.tar.gz
  sha256: edf012d33acb1b2cdd42cb0c7907c5af0717170a9cfd6500f161f80face7778d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - importlib_metadata
    - macro-kit
    - magic-class >=0.7.3
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - pandas
    - psygnal
    - python >=3.9
    - qtpy
    - scipy

test:
  imports:
    - napari_filaments
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/hanjinliu/napari-filaments
  summary: A napari plugin for filament analysis
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
    - jaimergp
