{% set name = "napari-filaments" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_filaments-{{ version }}.tar.gz
  sha256: 3986cfd578a21c1617c4b2414deb1476dc4baadcee5c9b481623be38dd685e91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magic-class >=0.6.7
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - scipy

test:
  imports:
    - napari_filaments
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hanjinliu/napari-filaments
  summary: A napari plugin for filament analysis
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
    - jaimergp
